package org.telegram.messenger.multigram;

import android.content.Context;
import android.util.SparseIntArray;

import org.telegram.messenger.ApplicationLoader;
import org.telegram.ui.ActionBar.Theme;

import java.io.File;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

/**
 * Palette fix for generated accents ("overlay A", see multigram/palette-fix/README.md).
 *
 * Stock Telegram colours already fail WCAG contrast on many text/background pairs, so a randomly
 * generated accent is only readable on top of this fix. It has three parts:
 * <ul>
 *   <li>static colour changes (ThemeColors defaults, bundled .attheme lines) and extra
 *       accent-exclusion keys ({@link #addAccentExclusions}), which apply to every accent;</li>
 *   <li>the on-accent rule: marks drawn on accent-coloured fills (compose pencil, unread digits,
 *       filled-button text, checkmarks, send and record glyphs...) become white or
 *       {@link #ON_ACCENT_DARK}, whichever has the higher contrast with the fill, and the muted unread
 *       badge gets a neutral fill that passes with the chosen digit colour. It runs only for runtime
 *       accents ({@link #isRuntimeAccent}: generated by MultiGram or made on this device), never for
 *       stock presets, Telegram's server themes, other people's cloud themes or Monet themes
 *       ({@link #isActiveFor}); per-chat themes follow the global state ({@link #applyToColorMap});</li>
 *   <li>the out-bubble text guard in Theme.ThemeAccent.fillAccentColors (runtime accents only).</li>
 * </ul>
 */
public final class PaletteFix {

    /**
     * Stock preset accents have ids up to 99 (id 100 is a custom accent migrated from very old app
     * versions, treated as stock). Every accent a ThemeInfo creates later gets ++lastAccentId, so 101 and
     * up: MultiGram's generated accents, accents the user makes in the theme editor, and also accents of
     * Telegram's server themes and of cloud themes, which {@link #isRuntimeAccent} excludes by their info.
     */
    public static final int LAST_STOCK_ACCENT_ID = 100;

    public static final int ON_ACCENT_LIGHT = 0xffffffff;
    /** The lightest near-black for which max(contrast(white), contrast(this)) >= 4.5 on any fill (min 4.51). */
    public static final int ON_ACCENT_DARK = 0xff050505;

    /** Contrast targets with headroom over WCAG 4.5 (text) and 3.0 (icons) for accent solvers. */
    public static final double TARGET_TEXT_CONTRAST = 4.6;
    public static final double TARGET_ICON_CONTRAST = 3.1;

    private static final double[] SRGB_LIN = new double[256];
    /** Theme key -> {muted badge fill with white digits, muted badge fill with near-black digits}. */
    private static final HashMap<String, int[]> MUTED_FILL = new HashMap<>();
    /** Bundled assets whose cached copy was already checked in this process ({@link #isStaleAssetCopy}). */
    private static final HashSet<String> CHECKED_ASSETS = new HashSet<>();
    private static long appUpdateTime = -1;

    static {
        for (int i = 0; i < 256; i++) {
            double c = i / 255.0;
            SRGB_LIN[i] = c <= 0.04045 ? c / 12.92 : StrictMath.pow((c + 0.055) / 1.055, 2.4);
        }
        int[] light = {0xff73777b, 0xffbec3c7};
        MUTED_FILL.put("Blue", light);
        MUTED_FILL.put("Arctic Blue", light);
        MUTED_FILL.put("Day", light);
        MUTED_FILL.put("Dark Blue", new int[]{0xff3e5263, 0xff63798b});
        MUTED_FILL.put("Night", new int[]{0xff454545, 0xff777676});
    }

    /**
     * Theme.key_* are assigned with colorsCount++ in Theme's static initializer, so they are not
     * compile-time constants. This holder is initialised on first use, after those fields are set.
     */
    private static final class Keys {
        /** (content, fill) pairs. */
        static final int[] ON_ACCENT = {
                Theme.key_chats_actionIcon, Theme.key_chats_actionBackground,
                Theme.key_chats_unreadCounterText, Theme.key_chats_unreadCounter,
                Theme.key_featuredStickers_buttonText, Theme.key_featuredStickers_addButton,
                Theme.key_checkboxSquareCheck, Theme.key_checkboxSquareBackground,
                Theme.key_dialogRoundCheckBoxCheck, Theme.key_dialogRoundCheckBox,
                Theme.key_chat_goDownButtonCounter, Theme.key_chat_goDownButtonCounterBackground,
                Theme.key_dialogCheckboxSquareCheck, Theme.key_dialogCheckboxSquareBackground,
                Theme.key_chat_attachCheckBoxCheck, Theme.key_chat_attachCheckBoxBackground,
                Theme.key_chat_inMediaIcon, Theme.key_chat_inLoader,
                Theme.key_chat_inContactIcon, Theme.key_chat_inContactBackground,
                Theme.key_picker_badgeText, Theme.key_picker_badge,
                Theme.key_dialogFloatingIcon, Theme.key_dialogFloatingButton,
                // not in overlay A: mic/camera/send glyphs of the voice-record circle and the
                // send-as menu button, drawn on chat_messagePanelVoiceBackground
                Theme.key_chat_messagePanelVoicePressed, Theme.key_chat_messagePanelVoiceBackground
        };
        /** Keys that fall back to chats_unreadCounterMuted; they keep their colour when it changes. */
        static final int[] MUTED_PINS = {
                Theme.key_avatar_backgroundArchived,
                Theme.key_chats_archivePinBackground,
                Theme.key_chats_archivePullDownBackground,
                Theme.key_checkboxDisabled
        };
        /** content key -> fill key. */
        static final SparseIntArray FILL_OF = new SparseIntArray();

        static {
            for (int i = 0; i < ON_ACCENT.length; i += 2) {
                FILL_OF.put(ON_ACCENT[i], ON_ACCENT[i + 1]);
            }
        }
    }

    private static volatile boolean globalActive;

    private PaletteFix() {
    }

    /**
     * Keys that must not follow the accent re-tint (neutral greys and the grey settings background).
     * Called once from Theme's static initializer with Theme.themeAccentExclusionKeys.
     */
    public static void addAccentExclusions(Set<Integer> exclusions) {
        exclusions.add(Theme.key_windowBackgroundGray);
        exclusions.add(Theme.key_windowBackgroundWhiteGrayText);
        exclusions.add(Theme.key_windowBackgroundWhiteGrayText2);
        exclusions.add(Theme.key_windowBackgroundWhiteGrayText4);
        exclusions.add(Theme.key_chats_message);
        exclusions.add(Theme.key_chats_date);
        exclusions.add(Theme.key_actionBarDefaultSubtitle);
        exclusions.add(Theme.key_chat_inTimeText);
        exclusions.add(Theme.key_chat_inFileInfoText);
        exclusions.add(Theme.key_chat_inViews);
        exclusions.add(Theme.key_chat_messagePanelHint);
        exclusions.add(Theme.key_chat_messagePanelIcons);
        exclusions.add(Theme.key_chat_topPanelMessage);
    }

    /**
     * Whether the accent was generated by MultiGram or made by the user on this device: id above
     * {@link #LAST_STOCK_ACCENT_ID} and no server theme behind it, or a server theme this user created
     * (a custom accent keeps the rule after the user shares it). Accents of Telegram's own server themes
     * (Chat Settings carousel, account.getThemes) and of cloud themes installed from someone else's
     * link also get ids above 100 but carry their TL_theme in accent.info, so they stay stock.
     * Also the guard of the out-bubble black/white text block in Theme.ThemeAccent.fillAccentColors.
     */
    public static boolean isRuntimeAccent(Theme.ThemeAccent accent) {
        return accent != null && accent.id > LAST_STOCK_ACCENT_ID && (accent.info == null || accent.info.creator);
    }

    /**
     * Whether the on-accent rule applies to colours built from this accent of this theme: the accent is
     * a runtime one ({@link #isRuntimeAccent}), the theme is not a Monet theme, and Theme.getColor would
     * not serve the stock defaults for it anyway (on Blue, an accent with the default accent colour, see
     * ThemeInfo.isDefaultMainAccent). Stock presets, server themes and chat-theme accents give false.
     *
     * @param theme the theme the colours are built for, or null to use accent.parentTheme
     */
    public static boolean isActiveFor(Theme.ThemeInfo theme, Theme.ThemeAccent accent) {
        if (!isRuntimeAccent(accent)) {
            return false;
        }
        if (theme == null) {
            theme = accent.parentTheme;
        }
        if (theme == null) {
            return true;
        }
        if (theme.isMonet()) {
            return false;
        }
        if (theme.firstAccentIsDefault && theme.themeAccentsMap != null) {
            Theme.ThemeAccent defaultAccent = theme.themeAccentsMap.get(Theme.DEFALT_THEME_ACCENT_ID);
            if (defaultAccent != null && defaultAccent.accentColor == accent.accentColor) {
                return false;
            }
        }
        return true;
    }

    /** Whether the global colours (Theme.getColor) currently carry the on-accent rule. */
    public static boolean isGlobalActive() {
        return globalActive;
    }

    /**
     * Global hook. Called at the end of Theme.refreshThemeColors, after fillAccentColors and the
     * calculated colours, with the new currentColors. Fills are read through
     * Theme.getColor(key, null, true), so theme-switch animation values are ignored.
     */
    public static void applyToCurrentColors(Theme.ThemeInfo theme, Theme.ThemeAccent accent, SparseIntArray currentColors) {
        boolean active = isActiveFor(theme, accent);
        globalActive = active;
        if (active) {
            apply(theme, currentColors, true);
        }
    }

    /**
     * Map-based hook. Call right after accent.fillAccentColors(noAccent, colors) wherever a
     * standalone colour map is built for a theme (chat themes, previews, exported theme files).
     * Missing keys resolve like Theme.getColor on that map (fallback key, then default colour).
     * <ul>
     *   <li>A map of an installed theme's accent gets the rule iff {@link #isActiveFor}(theme, accent),
     *       i.e. exactly when that accent gets it globally, so maps of stock accents stay stock.</li>
     *   <li>A per-chat theme (an accent in theme.chatAccentsByThemeId, built by EmojiThemes.createColors)
     *       gets the rule iff the global rule is active and the map is for the current light/dark mode,
     *       so a themed chat's marks follow the user's style: stock when the user's accent is stock,
     *       readable on the chat theme's own fills when the style is generated.</li>
     * </ul>
     */
    public static void applyToColorMap(Theme.ThemeInfo theme, Theme.ThemeAccent accent, SparseIntArray colors) {
        if (colors == null || accent == null) {
            return;
        }
        if (theme == null) {
            theme = accent.parentTheme;
        }
        if (isActiveFor(theme, accent) || isChatThemeAccent(theme, accent) && isGlobalActiveFor(theme)) {
            apply(theme, colors, false);
        }
    }

    private static boolean isChatThemeAccent(Theme.ThemeInfo theme, Theme.ThemeAccent accent) {
        return theme != null && theme.chatAccentsByThemeId != null && theme.chatAccentsByThemeId.indexOfValue(accent) >= 0;
    }

    private static boolean isGlobalActiveFor(Theme.ThemeInfo theme) {
        if (!globalActive || theme.isMonet()) {
            return false;
        }
        Theme.ThemeInfo active = Theme.getActiveTheme();
        return active != null && active.isDark() == theme.isDark();
    }

    /**
     * For upstream code that draws a glyph or text in a fixed colour (usually white) on an accent fill,
     * such as the send buttons (ChatActivityEnterView.SendButton). Returns 0, meaning "keep the stock
     * colour", unless the global on-accent rule is active; then white or {@link #ON_ACCENT_DARK},
     * whichever contrasts more with the fill.
     *
     * @param fill the colour the glyph is drawn on, or 0 when it is not drawn on a fill
     */
    public static int getGlyphColorOnFill(int fill) {
        if (!globalActive || fill == 0) {
            return 0;
        }
        return onAccentContent(fill, Theme.getColor(Theme.key_windowBackgroundWhite) | 0xff000000);
    }

    /**
     * Theme.getAssetFile hook: whether the copy of a bundled asset cached in filesDir is older than the
     * installed app. getAssetFile re-copies an asset only when its size changes, and the palette fix
     * changes some .attheme values without changing the file size (arctic, bluebubbles), so an update
     * over an older build would keep the old values. Answers true at most once per file and process,
     * so a wrong device clock costs one extra copy per start at worst.
     */
    public static boolean isStaleAssetCopy(File file) {
        synchronized (CHECKED_ASSETS) {
            if (!CHECKED_ASSETS.add(file.getName())) {
                return false;
            }
            if (appUpdateTime < 0) {
                try {
                    Context context = ApplicationLoader.applicationContext;
                    appUpdateTime = context.getPackageManager().getPackageInfo(context.getPackageName(), 0).lastUpdateTime;
                } catch (Throwable e) {
                    appUpdateTime = 0;
                }
            }
            return file.exists() && file.lastModified() < appUpdateTime;
        }
    }

    /**
     * For resources providers that override some colours on top of the global theme: returns the
     * colour for a key the override map does not contain. When the global on-accent rule is active
     * and the map overrides the fill under this content key, the content is recomputed for that fill
     * instead of taking the global value (which was chosen for a different fill).
     */
    public static int getOverrideFallbackColor(SparseIntArray overrides, int key) {
        if (globalActive && overrides != null) {
            int fill = Keys.FILL_OF.get(key, -1);
            if (fill != -1) {
                int index = overrides.indexOfKey(fill);
                if (index >= 0) {
                    int pageIndex = overrides.indexOfKey(Theme.key_windowBackgroundWhite);
                    int page = pageIndex >= 0 ? overrides.valueAt(pageIndex) : Theme.getColor(Theme.key_windowBackgroundWhite);
                    return onAccentContent(overrides.valueAt(index), page | 0xff000000);
                }
            }
        }
        return Theme.getColor(key);
    }

    private static void apply(Theme.ThemeInfo theme, SparseIntArray colors, boolean global) {
        int[] pairs = Keys.ON_ACCENT;
        int page = resolve(colors, Theme.key_windowBackgroundWhite, global) | 0xff000000;
        int[] content = new int[pairs.length / 2];
        for (int i = 0; i < pairs.length; i += 2) {
            content[i / 2] = onAccentContent(resolve(colors, pairs[i + 1], global), page);
        }
        for (int i = 0; i < pairs.length; i += 2) {
            colors.put(pairs[i], content[i / 2]);
        }
        int[] muted = theme != null ? MUTED_FILL.get(theme.getKey()) : null;
        if (muted != null) {
            for (int key : Keys.MUTED_PINS) {
                if (colors.indexOfKey(key) < 0) {
                    colors.put(key, resolve(colors, key, global));
                }
            }
            boolean whiteDigits = colors.get(Theme.key_chats_unreadCounterText) == ON_ACCENT_LIGHT;
            colors.put(Theme.key_chats_unreadCounterMuted, whiteDigits ? muted[0] : muted[1]);
        }
    }

    private static int resolve(SparseIntArray colors, int key, boolean global) {
        if (global) {
            return Theme.getColor(key, null, true);
        }
        int index = colors.indexOfKey(key);
        if (index >= 0) {
            return colors.valueAt(index);
        }
        int fallbackKey = Theme.getFallbackKeys().get(key, -1);
        if (fallbackKey != -1) {
            index = colors.indexOfKey(fallbackKey);
            if (index >= 0) {
                return colors.valueAt(index);
            }
        }
        return Theme.getDefaultColor(key);
    }

    /** White or {@link #ON_ACCENT_DARK}, whichever contrasts more with fill composited over page; ties go to white. */
    public static int onAccentContent(int fill, int page) {
        int f = compositeOver(fill, page);
        return contrast(ON_ACCENT_LIGHT, f) >= contrast(ON_ACCENT_DARK, f) ? ON_ACCENT_LIGHT : ON_ACCENT_DARK;
    }

    /** Integer src-over of fg on an opaque bg, (a*x + (255-a)*y + 127) / 255 per channel; result is opaque. */
    public static int compositeOver(int fg, int bg) {
        int a = fg >>> 24;
        if (a == 255) {
            return fg;
        }
        int ia = 255 - a;
        int r = (((fg >> 16) & 255) * a + ((bg >> 16) & 255) * ia + 127) / 255;
        int g = (((fg >> 8) & 255) * a + ((bg >> 8) & 255) * ia + 127) / 255;
        int b = ((fg & 255) * a + (bg & 255) * ia + 127) / 255;
        return 0xff000000 | (r << 16) | (g << 8) | b;
    }

    /** WCAG 2.2 relative luminance of the RGB part of color (alpha ignored). */
    public static double luminance(int color) {
        return 0.2126 * SRGB_LIN[(color >> 16) & 255] + 0.7152 * SRGB_LIN[(color >> 8) & 255] + 0.0722 * SRGB_LIN[color & 255];
    }

    /** WCAG 2.2 contrast ratio of two opaque colours, 1.0 to 21.0. */
    public static double contrast(int color1, int color2) {
        double l1 = luminance(color1);
        double l2 = luminance(color2);
        return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
    }
}
